# Generated by Django 2.2.3 on 2019-08-11 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0012_auto_20190811_2238'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-date_created']},
        ),
    ]
